sap.ui.define([                                                                                                                                                                                                                                                
	"sap/ui/core/mvc/Controller"                                                                                                                                                                                                                                  
],                                                                                                                                                                                                                                                             
	/**                                                                                                                                                                                                                                                           
	 * @param {typeof sap.ui.core.mvc.Controller} Controller                                                                                                                                                                                                      
	 */                                                                                                                                                                                                                                                           
	function (Controller) {                                                                                                                                                                                                                                       
		"use strict";                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                               
		return Controller.extend("monstersvsfs.controller.MonsterList", {                                                                                                                                                                                            
			onInit: function () {                                                                                                                                                                                                                                       
				var oModel = this.getOwnerComponent().getModel("Monster");&nbsp;                                                                                                                                                                                           
				this.getView().setModel(oModel);                                                                                                                                                                                                                           
			},                                                                                                                                                                                                                                                          
			// Searching for Monster based on what the user puts in the Search Box                                                                                                                                                                                      
			onSearch: function (oEvent) {                                                                                                                                                                                                                               
				// add filter for search                                                                                                                                                                                                                                   
				var aFilters = [];                                                                                                                                                                                                                                         
				var sQuery = oEvent.getSource().getValue();                                                                                                                                                                                                                
				if (sQuery && sQuery.length > 0) {                                                                                                                                                                                                                         
					var filter = new sap.ui.model.Filter("Name",                                                                                                                                                                                                              
						sap.ui.model.FilterOperator.Contains, sQuery);                                                                                                                                                                                                           
					aFilters.push(filter);                                                                                                                                                                                                                                    
				}                                                                                                                                                                                                                                                          
				// update list binding                                                                                                                                                                                                                                     
				var oTable = this.getView().byId("idMonstersTable");                                                                                                                                                                                                       
				var binding = oTable.getBinding("items");                                                                                                                                                                                                                  
				binding.filter(aFilters, "Application");                                                                                                                                                                                                                   
			},                                                                                                                                                                                                                                                          
			// Call up the Monster Detail Dialog Box when Monster Selected                                                                                                                                                                                              
			onMonsterSelected: function (oEvent) {                                                                                                                                                                                                                      
				console.log('onMonsterSelected ' + oEvent.getSource().getBindingContextPath());                                                                                                                                                                            
				if (this._monsterDetailDialog === undefined) {                                                                                                                                                                                                             
					this._monsterDetailDialog = new sap.ui.xmlfragment(                                                                                                                                                                                                       
				    		"monstersvsfs.view.MonsterDetail", this);                                                                                                                                                                                                            
					this._monsterDetailDialog.setModel(this.getView().getModel());                                                                                                                                                                                            
					this.getView().addDependent(this._monsterDetailDialog);                                                                                                                                                                                                   
				}                                                                                                                                                                                                                                                          
				this._monsterDetailDialog.open();                                                                                                                                                                                                                          
				this._monsterDetailDialog.bindElement({                                                                                                                                                                                                                    
					path: oEvent.getSource().getBindingContextPath(),                                                                                                                                                                                                         
					parameters: {                                                                                                                                                                                                                                             
						expand: 'FromMonstersToMonsterItems'                                                                                                                                                                                                                     
					}                                                                                                                                                                                                                                                         
				});                                                                                                                                                                                                                                                        
			},                                                                                                                                                                                                                                                          
			onMonsterDetailDialogCancel: function (oEvent) {                                                                                                                                                                                                            
				this._monsterDetailDialog.close();                                                                                                                                                                                                                         
			},                                                                                                                                                                                                                                                          
			onMonsterDelete: function (oEvent) {                                                                                                                                                                                                                        
				var oModel = this.getView().getModel();                                                                                                                                                                                                                    
				var oPath = oEvent.getSource().getBindingContext().getPath();                                                                                                                                                                                              
                                                                                                                                                                                                                                                               
				oModel.remove(oPath, {                                                                                                                                                                                                                                     
					sucess: this._monsterDeleteSuccess,                                                                                                                                                                                                                       
					error: this._monsterDeleteError                                                                                                                                                                                                                           
				});                                                                                                                                                                                                                                                        
			},                                                                                                                                                                                                                                                          
			_monsterDeleteSuccess: function (oEvent) {                                                                                                                                                                                                                  
				this.onMonsterDetailDialogCancel();                                                                                                                                                                                                                        
				sap.m.MessageToast.show('Deleted', {                                                                                                                                                                                                                       
					duration: 5000,                                                                                                                                                                                                                                           
					my: 'center center',                                                                                                                                                                                                                                      
					at: 'center center'                                                                                                                                                                                                                                       
				});                                                                                                                                                                                                                                                        
			},                                                                                                                                                                                                                                                          
			_monsterDeleteError: function (oEvent) {                                                                                                                                                                                                                    
				var oResponse = JSON.parse(oEvent.response.body);                                                                                                                                                                                                          
				if (oResponse.error.message) {                                                                                                                                                                                                                             
					sap.m.MessageBox.alert(oResponse.error.message.value);                                                                                                                                                                                                    
				} else {                                                                                                                                                                                                                                                   
					sap.m.MessageBox.alert('An Unknown Error Detected');                                                                                                                                                                                                      
				}                                                                                                                                                                                                                                                          
			},                                                                                                                                                                                                                                                          
			handleOpen : function (oEvent) {                                                                                                                                                                                                                            
				var oButton = oEvent.getSource();                                                                                                                                                                                                                          
		                                                                                                                                                                                                                                                             
				// create action sheet only once                                                                                                                                                                                                                           
				if (!this._actionSheet) {                                                                                                                                                                                                                                  
				  this._actionSheet = sap.ui.xmlfragment(                                                                                                                                                                                                                  
					"monstersvsfs.view.ActionSheet", this);                                                                                                                                                                                                                   
				  this.getView().addDependent(this._actionSheet);                                                                                                                                                                                                          
				}                                                                                                                                                                                                                                                          
		                                                                                                                                                                                                                                                             
				this._actionSheet.openBy(oButton);                                                                                                                                                                                                                         
			  }                                                                                                                                                                                                                                                         
		});                                                                                                                                                                                                                                                          
	}                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
);                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               