CLASS LCL_ZEI_EXCEL_EXTENSIONS DEFINITION DEFERRED.
CLASS ZCL_EXCEL_WORKSHEET DEFINITION LOCAL FRIENDS LCL_ZEI_EXCEL_EXTENSIONS.
CLASS LCL_ZEI_EXCEL_EXTENSIONS DEFINITION.
PUBLIC SECTION.
CLASS-DATA OBJ TYPE REF TO LCL_ZEI_EXCEL_EXTENSIONS. "#EC NEEDED
DATA CORE_OBJECT TYPE REF TO ZCL_EXCEL_WORKSHEET . "#EC NEEDED
 INTERFACES  IOW_ZEI_EXCEL_EXTENSIONS.
  METHODS:
   CONSTRUCTOR IMPORTING CORE_OBJECT
     TYPE REF TO ZCL_EXCEL_WORKSHEET OPTIONAL.
ENDCLASS.
CLASS LCL_ZEI_EXCEL_EXTENSIONS IMPLEMENTATION.
METHOD CONSTRUCTOR.
  ME->CORE_OBJECT = CORE_OBJECT.
ENDMETHOD.

METHOD IOW_ZEI_EXCEL_EXTENSIONS~CALCULATE_COLUMN_WIDTHS.
*"------------------------------------------------------------------------*
*" Declaration of Overwrite-method, do not insert any comments here please!
*"
*"methods CALCULATE_COLUMN_WIDTHS
*"  raising
*"    ZCX_EXCEL .
*"------------------------------------------------------------------------*

   zcl_excel_extender=>calculate_column_widths( core_object ).

ENDMETHOD.
ENDCLASS.
