interface ZIF_4CDS_MONSTER_DELIVERIES_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF Z4CDS_MONSTER_DELIVERIES,
 ACTIVATION                     TYPE /BOBF/ACT_KEY VALUE '005056B074C91EDBA7D08397A17B412A',
 CREATE_Z4CDS_MONSTER_DELIVERIE TYPE /BOBF/ACT_KEY VALUE '005056B074C91EDBA7D08397A178812A',
 DELETE_Z4CDS_MONSTER_DELIVERIE TYPE /BOBF/ACT_KEY VALUE '005056B074C91EDBA7D08397A179012A',
 EDIT                           TYPE /BOBF/ACT_KEY VALUE '005056B074C91EDBA7D08397A17B212A',
 LOCK_Z4CDS_MONSTER_DELIVERIES  TYPE /BOBF/ACT_KEY VALUE '005056B074C91EDBA7D08397A177C12A',
 PREPARATION                    TYPE /BOBF/ACT_KEY VALUE '005056B074C91EDBA7D08397A17B812A',
 SAVE_Z4CDS_MONSTER_DELIVERIES  TYPE /BOBF/ACT_KEY VALUE '005056B074C91EDBA7D08397A179812A',
 UNLOCK_Z4CDS_MONSTER_DELIVERIE TYPE /BOBF/ACT_KEY VALUE '005056B074C91EDBA7D08397A178012A',
 UPDATE_Z4CDS_MONSTER_DELIVERIE TYPE /BOBF/ACT_KEY VALUE '005056B074C91EDBA7D08397A178C12A',
 VALIDATE_Z4CDS_MONSTER_DELIVER TYPE /BOBF/ACT_KEY VALUE '005056B074C91EDBA7D08397A179412A',
 VALIDATION                     TYPE /BOBF/ACT_KEY VALUE '005056B074C91EDBA7D08397A17B612A',
      END OF Z4CDS_MONSTER_DELIVERIES,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF Z4CDS_MONSTER_DELIVERIES,
        BEGIN OF EDIT,
 PRESERVE_CHANGES               TYPE STRING VALUE 'PRESERVE_CHANGES',
        END OF EDIT,
        BEGIN OF LOCK_Z4CDS_MONSTER_DELIVERIES,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_Z4CDS_MONSTER_DELIVERIES,
        BEGIN OF PREPARATION,
 SIDEEFFECTSQUALIFIER           TYPE STRING VALUE 'SIDEEFFECTSQUALIFIER',
        END OF PREPARATION,
        BEGIN OF UNLOCK_Z4CDS_MONSTER_DELIVERIE,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_Z4CDS_MONSTER_DELIVERIE,
        BEGIN OF VALIDATION,
 SIDEEFFECTSQUALIFIER           TYPE STRING VALUE 'SIDEEFFECTSQUALIFIER',
        END OF VALIDATION,
      END OF Z4CDS_MONSTER_DELIVERIES,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF Z4CDS_MONSTER_DELIVERIES,
 ACTIVE_ENTITY_KEY              TYPE /BOBF/OBM_ALTKEY_KEY VALUE '005056B074C91EDBA7D08397A17B012A',
      END OF Z4CDS_MONSTER_DELIVERIES,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF Z4CDS_MONSTER_DELIVERIES,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056B074C91EDBA7D08397A177A12A',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056B074C91EDBA7D08397A177612A',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056B074C91EDBA7D08397A178612A',
      END OF Z4CDS_MONSTER_DELIVERIES,
      BEGIN OF Z4CDS_MONSTER_DELIVERIES_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056B074C91EDBA7D08397A179E12A',
      END OF Z4CDS_MONSTER_DELIVERIES_LOCK,
      BEGIN OF Z4CDS_MONSTER_DELIVERIES_MESSA,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056B074C91EDBA7D08397A179C12A',
      END OF Z4CDS_MONSTER_DELIVERIES_MESSA,
      BEGIN OF Z4CDS_MONSTER_DELIVERIES_PROPE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056B074C91EDBA7D08397A17A012A',
      END OF Z4CDS_MONSTER_DELIVERIES_PROPE,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF Z4CDS_MONSTER_DELIVERIES,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF Z4CDS_MONSTER_DELIVERIES,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '005056B074C91EDBA7D08397A176C12A' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'Z4CDS_MONSTER_DELIVERIES' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF Z4CDS_MONSTER_DELIVERIES,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '005056B074C91EDBA7D08397A17BA12A',
 CENTRAL_ADMIN_DATA             TYPE /BOBF/DET_KEY VALUE '005056B074C91EDBA7D08397A17BC12A',
 DELETE_DRAFT_WHN_ACTIVE_DELETE TYPE /BOBF/DET_KEY VALUE '005056B074C91EDBA7D08397A17CA12A',
 DRAFT_ACTION_CONTROL           TYPE /BOBF/DET_KEY VALUE '005056B074C91EDBA7D08397A17C812A',
 DRAFT_SYS_ADMIN_DATA           TYPE /BOBF/DET_KEY VALUE '005056B074C91EDBA7D08397A17BE12A',
 DURABLE_LOCK_CLEANUP_CLEANUP   TYPE /BOBF/DET_KEY VALUE '005056B074C91EDBA7D08397A17C612A',
 DURABLE_LOCK_CLEANUP_DELETE    TYPE /BOBF/DET_KEY VALUE '005056B074C91EDBA7D08397A17C012A',
 DURABLE_LOCK_CLEANUP_FAIL_SAVE TYPE /BOBF/DET_KEY VALUE '005056B074C91EDBA7D08397A17C412A',
 DURABLE_LOCK_CLEANUP_SUCC_SAVE TYPE /BOBF/DET_KEY VALUE '005056B074C91EDBA7D08397A17C212A',
      END OF Z4CDS_MONSTER_DELIVERIES,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 DRAFT_CONSISTENCY              TYPE /BOBF/OBM_GROUP_KEY VALUE '005056B074C91EDBA7D08397A17A412A',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 Z4CDS_MONSTER_DELIVERIES       TYPE /BOBF/OBM_NODE_KEY VALUE '005056B074C91EDBA7D08397A177012A',
 Z4CDS_MONSTER_DELIVERIES_LOCK  TYPE /BOBF/OBM_NODE_KEY VALUE '005056B074C91EDBA7D08397A177812A',
 Z4CDS_MONSTER_DELIVERIES_MESSA TYPE /BOBF/OBM_NODE_KEY VALUE '005056B074C91EDBA7D08397A177412A',
 Z4CDS_MONSTER_DELIVERIES_PROPE TYPE /BOBF/OBM_NODE_KEY VALUE '005056B074C91EDBA7D08397A178412A',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF Z4CDS_MONSTER_DELIVERIES,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  DELIVERY_NUMBER                TYPE STRING VALUE 'DELIVERY_NUMBER',
  ORDER_NUMBER                   TYPE STRING VALUE 'ORDER_NUMBER',
  ORDER_ITEM                     TYPE STRING VALUE 'ORDER_ITEM',
  MONSTER_NUMBER                 TYPE STRING VALUE 'MONSTER_NUMBER',
  MONSTER_NAME                   TYPE STRING VALUE 'MONSTER_NAME',
  CASTLE_NUMBER                  TYPE STRING VALUE 'CASTLE_NUMBER',
  VILLAGE_NUMBER                 TYPE STRING VALUE 'VILLAGE_NUMBER',
  VILLAGE_ADDRESS                TYPE STRING VALUE 'VILLAGE_ADDRESS',
  TASK_DESCRIPTION               TYPE STRING VALUE 'TASK_DESCRIPTION',
  DUE_DATE                       TYPE STRING VALUE 'DUE_DATE',
  DUE_TIME                       TYPE STRING VALUE 'DUE_TIME',
  ACTUAL_DATE                    TYPE STRING VALUE 'ACTUAL_DATE',
  ACTUAL_TIME                    TYPE STRING VALUE 'ACTUAL_TIME',
  CURRENT_STATUS                 TYPE STRING VALUE 'CURRENT_STATUS',
  ACTIVEUUID                     TYPE STRING VALUE 'ACTIVEUUID',
  HASACTIVEENTITY                TYPE STRING VALUE 'HASACTIVEENTITY',
  DRAFTENTITYCREATIONDATETIME    TYPE STRING VALUE 'DRAFTENTITYCREATIONDATETIME',
  DRAFTENTITYLASTCHANGEDATETIME  TYPE STRING VALUE 'DRAFTENTITYLASTCHANGEDATETIME',
  DRAFTENTITYCONSISTENCYSTATUS   TYPE STRING VALUE 'DRAFTENTITYCONSISTENCYSTATUS',
  ISACTIVEENTITY                 TYPE STRING VALUE 'ISACTIVEENTITY',
      END OF Z4CDS_MONSTER_DELIVERIES,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF Z4CDS_MONSTER_DELIVERIES,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '005056B074C91EDBA7D08397A177212A',
      END OF Z4CDS_MONSTER_DELIVERIES,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_STATUS_VARIABLE,
      BEGIN OF Z4CDS_MONSTER_DELIVERIES,
 DRAFT_CONSISTENCY_STATUS       TYPE /BOBF/STA_VAR_KEY VALUE '005056B074C91EDBA7D08397A17A212A',
      END OF Z4CDS_MONSTER_DELIVERIES,
    END OF SC_STATUS_VARIABLE .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF Z4CDS_MONSTER_DELIVERIES,
 DURABLE_LOCK_CREATE_FOR_NEW    TYPE /BOBF/VAL_KEY VALUE '005056B074C91EDBA7D08397A17CC12A',
      END OF Z4CDS_MONSTER_DELIVERIES,
    END OF SC_VALIDATION .
endinterface.
